# Generated by Django 4.2.30 on 2026-07-30 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('sast_tool', models.CharField(choices=[('BANDIT', 'Bandit'), ('SEMGREP', 'Semgrep'), ('PYTEST', 'Pytest'), ('SYNTAX_CHECK', 'Syntax Check')], max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('exit_code', models.IntegerField(default=0)),
                ('stdout_log', models.TextField(blank=True, null=True)),
                ('stderr_log', models.TextField(blank=True, null=True)),
                ('security_score', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='patches.patch')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
