# Generated by Django 4.2.30 on 2026-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
