# Generated by Django 4.2.30 on 2026-07-30 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('suggested_by_agent', models.CharField(max_length=100)),
                ('diff_content', models.TextField()),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('PR_OPENED', 'PR Opened'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='GENERATED', max_length=20)),
                ('pull_request_url', models.URLField(blank=True, max_length=500, null=True)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='reviews.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
