# Generated by Django 4.2.30 on 2026-07-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='ai_response_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
