# Generated by Django 4.2.30 on 2026-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_patch_ai_response_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='pr_preview_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('PR_PREVIEW', 'PR Preview'), ('PR_OPENED', 'PR Opened'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='GENERATED', max_length=20),
        ),
    ]
