# Generated by Django 4.2.30 on 2026-07-30 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('github_repo_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('clone_url', models.URLField(blank=True, max_length=500, null=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('is_private', models.BooleanField(default=True)),
                ('language', models.CharField(default='python', max_length=50)),
                ('ast_index_status', models.CharField(choices=[('NOT_INDEXED', 'Not Indexed'), ('INDEXING', 'Indexing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='NOT_INDEXED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ZipUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('s3_object_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extracted_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_uploads', to='repositories.repository')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
