# Generated by Django 4.2.30 on 2026-07-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Repositories'},
        ),
    ]
