# Generated by Django 5.1.15 on 2026-10-05 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTuningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('sagemaker_job_name', models.CharField(max_length=255, unique=True)),
                ('base_model', models.CharField(max_length=255)),
                ('output_adapter_s3_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='STARTING', max_length=20)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('epochs', models.IntegerField(default=3)),
                ('learning_rate', models.FloatField(default=2e-05)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('suggested_by_agent', models.CharField(max_length=100)),
                ('diff_content', models.TextField()),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('PR_PREVIEW', 'PR Preview'), ('PR_OPENED', 'PR Opened'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='GENERATED', max_length=20)),
                ('pull_request_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ai_response_json', models.JSONField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('pr_preview_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('model_identifier', models.CharField(max_length=255)),
                ('benchmark_name', models.CharField(max_length=100)),
                ('precision_score', models.FloatField(default=0.0)),
                ('recall_score', models.FloatField(default=0.0)),
                ('pass_at_1_score', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('fine_tuning_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finetuningjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('action', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], max_length=20)),
                ('user_comments', models.TextField(blank=True, null=True)),
                ('modified_diff', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='core.patch')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('github_repo_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('clone_url', models.URLField(blank=True, max_length=500, null=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('is_private', models.BooleanField(default=True)),
                ('language', models.CharField(default='python', max_length=50)),
                ('ast_index_status', models.CharField(choices=[('NOT_INDEXED', 'Not Indexed'), ('INDEXING', 'Indexing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='NOT_INDEXED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual'), ('WEBHOOK', 'Webhook'), ('API_KEY', 'API Key'), ('SCHEDULE', 'Schedule')], default='MANUAL', max_length=20)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.repository')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('agent_name', models.CharField(max_length=100)),
                ('step_index', models.IntegerField()),
                ('thought', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='core.scan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('sast_tool', models.CharField(choices=[('BANDIT', 'Bandit'), ('SEMGREP', 'Semgrep'), ('PYTEST', 'Pytest'), ('SYNTAX_CHECK', 'Syntax Check')], max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('exit_code', models.IntegerField(default=0)),
                ('stdout_log', models.TextField(blank=True, null=True)),
                ('stderr_log', models.TextField(blank=True, null=True)),
                ('security_score', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='core.patch')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('cwe_id', models.CharField(blank=True, max_length=20, null=True)),
                ('owasp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('file_path', models.CharField(max_length=1024)),
                ('line_start', models.IntegerField()),
                ('line_end', models.IntegerField()),
                ('snippet', models.TextField()),
                ('code_context', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('context_line_start', models.IntegerField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('analysis_report', models.JSONField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='core.scan')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patch',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='core.vulnerability'),
        ),
        migrations.CreateModel(
            name='ZipUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUIDv4 identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp of initial record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of most recent record modification.')),
                ('s3_object_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extracted_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_uploads', to='core.repository')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
